apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ventas.fullname" . }}
  labels:
    app: {{ template "ventas.name" . }}
    project: {{ .Values.project }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "ventas.name" . }}
      project: {{ .Values.project }}
      component: {{ .Values.component }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ventas.name" . }}
        project: {{ .Values.project }}
        component: {{ .Values.component }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "ventas.fullname" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
