apiVersion: v1
kind: Service
metadata:
  name: {{ template "productos.fullname" . }}
  labels:
    app: {{ template "productos.name" . }}
    project: {{ .Values.project }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
  selector:
    app: {{ template "productos.name" . }}
    project: {{ .Values.project }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
