apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "reportes.fullname" . }}
  labels:
    app: {{ template "reportes.name" . }}
    project: {{ .Values.project }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ template "reportes.fullname" . }}
              servicePort: {{ .Values.service.port }}
